apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer-new
spec:
  selector:
    app: paytm-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
